Server/SEOBot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("orders.urls")),
]

Server/accounts/urls.py
from django.urls import path
from .views import CreateAccessUser, PasswordChangeView, password_success, UsersListView, UserDeleteView, UserUpdateView    

app_name = 'accounts'
urlpatterns = [
    path("access_user/", CreateAccessUser.as_view(), name="access_user"),
    path("password/", PasswordChangeView.as_view(), name="change_password"),
    path("users/", UsersListView.as_view(), name="users"),
    path("users/<int:pk>/delete/", UserDeleteView.as_view(), name="delete_user"),
    path("users/<int:pk>/update/", UserUpdateView.as_view(), name="update_user"),
]  

Server/orders/urls.py
from django.urls import path
from .views import *


app_name = 'orders'
urlpatterns = [
    # Order routes
    path("", ViewOrders.as_view(), name="list_of_orders"),
    path("result1", ViewKeyword.as_view(), name="ViewKeyword"),
    path('update-action/', update_order_action, name='update-action'),

    path("order/new/", CreateNewOrder.as_view(), name="create_order"),
    path("order/<int:pk>/delete/", DeleteOrder.as_view(), name="delete_order"),
    path("order/<int:pk>/update/", UpdateOrder.as_view(), name="update_order"),
    # Profile route
    path("profiles", ViewProfiles.as_view(), name="profile"),
    path("profile/new/", CreateNewProfile.as_view(), name="create_profile"),
    path("profile/<int:pk>/delete/", DeleteProfile.as_view(), name="delete_profile"),
    path("profile/<int:pk>/update/", UpdateProfile.as_view(), name="update_profile"),

    # API route
    path("api/get/orders/web", get_orders_web),
    path("api/get/random/user/web/<int:no>",get_random_proxy_details_web),
    path("api/get/random/user/mobile/<int:no>",get_random_proxy_details_mobile),
    path("api/get/orders/mobile", get_orders_mobile),
    path('update-reached-users/<int:pk>/', update_reached_users, name='update_reached_users'),
    path('update-reached-users-incomplete/<int:pk>/', update_reached_users_incomplete),
    path("api/set/profile/free/<int:pk>/",setProfileFree),
    path("api/get/number/of/profiles",get_number_of_profile_mobile),

    path('api/update-reached-numbers/<int:order_id>/', update_reached_users, name='update_reached_users'),
]

Server/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django import forms


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter email...'}),
    )
    first_name = forms.CharField(
        max_length=30,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter first name...'}),
    )
    last_name = forms.CharField(
        max_length=30,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter last name...'}),
    )
    is_staff = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}),
    )
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter username...'}),
    )
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter password...'}),
    )
    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm password...'}),
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'is_staff')


class PasswordChangeFormCustom(PasswordChangeForm):
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'placeholder': 'Enter old password...'}),
    )
    new_password1 = forms.CharField(
        max_length=100,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'placeholder': 'Enter new password...'}),
    )
    new_password2 = forms.CharField(
        max_length=100,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'placeholder': 'Confirm new password...'}),
    )

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'is_staff']

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'is_staff': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

Server/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.views import PasswordChangeView
from django.views import generic 
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from .forms import SignUpForm, PasswordChangeFormCustom, UserUpdateForm

class UsersListView(LoginRequiredMixin, generic.ListView):
    model = User
    template_name = "users.html"
    context_object_name = "users"
    paginate_by = 6 

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return redirect('orders:list_of_orders')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return User.objects.all().order_by('-date_joined')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Pagination
        users_list = self.get_queryset()
        page = self.request.GET.get('page', 1)
        paginator = Paginator(users_list, self.paginate_by)

        try:
            users_list = paginator.page(page)
        except PageNotAnInteger:
            users_list = paginator.page(1)
        except EmptyPage:
            users_list = paginator.page(paginator.num_pages)
        
        context['users'] = users_list
        return context


class UserDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = User
    template_name = "delete_user.html"
    success_url = reverse_lazy("accounts:users")

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk', None)
        return get_object_or_404(User, pk=pk)
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return redirect('orders:list_of_orders') 
        return super().dispatch(request, *args, **kwargs)
    
    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        messages.success(self.request, f"User&nbsp;<strong>{self.object.username}</strong>&nbsp;deleted successfully!")
        return response
    

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, f"User&nbsp;<strong>{self.object.username}</strong>&nbsp;deleted successfully!")
        return response


class UserUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = User
    template_name = "update_user.html"
    form_class = UserUpdateForm
    success_url = "accounts:users"

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk', None)
        return get_object_or_404(User, pk=pk)

    def get_success_url(self):
        return reverse_lazy('accounts:users')  # Redirect to the user list after successful update

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return redirect('orders:list_of_orders')  # Redirect to home if user is not staff
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, f"User&nbsp;<strong>{self.object.username}</strong>&nbsp;updated successfully!")
        return response


class CreateAccessUser(LoginRequiredMixin, generic.CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy("accounts:users")
    template_name = "registration/new_access_user.html"

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return redirect('orders:list_of_orders') 
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, f"User&nbsp;<strong>{self.object.username}</strong>&nbsp;successfully is created!")
        return response


class PasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    form_class = PasswordChangeFormCustom
    success_url = reverse_lazy('accounts:change_password')
    template_name = "registration/change_password.html"

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Password changed successfully!')
        return response


def password_success(request):
    return render(request, 'registration/password_success.html', {})

Server/accounts/templates/delete_user.html
{% block title %}
<title>Delete User</title>
{% endblock title %}

{% block content %}
<!-- Modal To Delete User -->
<div class="modal" id="confirmDeleteModal{{ user.pk }}" tabindex="-1" aria-labelledby="myModalLabel2" aria-hidden="true">    
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Confirm Delete</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true"></span>
            </button>
        </div>
        <div class="modal-body">
            <p>Are you sure you want to delete the user <strong>"{{ user.username }}"</strong>?</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            <form action="{% url 'accounts:delete_user' user.pk %}" method="POST">
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Delete">
              </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

Server/accounts/templates/update_user.html
{% extends "base.html" %}

{% block title %}
    <title>Update User</title>
{% endblock title %}

{% block content %}
        <div class="row justify-content-center">
            <div class="col-md-7 col-lg-5">

                {% block nav_links %}
                    <span class="d-flex align-items-center mb-2">
                        <a href="{% url 'orders:list_of_orders' %}" class="text-decoration-none text-secondary ">
                            <i class='bx bx-home fs-5 text-secondary' ></i>
                        </a>
                        <i class='bx bx-chevron-right fs-5 text-secondary' ></i>
                        <a href="{% url 'accounts:users' %}" class="text-decoration-none text-secondary">
                            All Users
                        </a>
                        <i class='bx bx-chevron-right fs-5 text-secondary' ></i>
                        <span class="text-secondary">Update User</span>
                    </span>
                {% endblock nav_links %}

                <div class="card shadow-sm p-4 mb-5 bg-white rounded">
                    <h2 class="text-success mt-1">Update User</h2>
                    <hr>
                    <div class="card-body">
                        <form method="post" >
                            {% csrf_token %}

                            <div class="mb-3">
                                <label for="{{ form.username.id_for_label }}" class="form-label">{{ form.username.label }}:</label>
                                <div class="input-group mb-3">
                                    <span class="input-group-text" id="basic-addon1">
                                        <i class='bx bxs-key fs-5' style='color:#4d524d'></i>
                                    </span>
                                    {{ form.username }}
                                </div>
                            </div>

                            <div class="mb-3">
                                <label for="{{ form.email.id_for_label }}" class="form-label">{{ form.email.label }}:</label>
                                <div class="input-group mb-3">
                                    <span class="input-group-text" id="basic-addon1">
                                        <i class='bx bxs-envelope fs-5' style='color:#4d524d'></i>
                                    </span>
                                    {{ form.email }}
                                </div>
                            </div>

                            <div class="mb-3">
                                <label for="{{ form.first_name.id_for_label }}" class="form-label">{{ form.first_name.label }}:</label>
                                <div class="input-group mb-3">
                                    <span class="input-group-text" id="basic-addon1">
                                        <i class='bx bxs-user fs-5' style='color:#4d524d'></i>
                                    </span>
                                    {{ form.first_name }}
                                </div>
                            </div>

                            <div class="mb-3">
                                <label for="{{ form.last_name.id_for_label }}" class="form-label">{{ form.last_name.label }}:</label>
                                <div class="input-group mb-3">
                                    <span class="input-group-text" id="basic-addon1">
                                        <i class='bx bxs-user fs-5' style='color:#4d524d'></i>
                                    </span>
                                    {{ form.last_name }}
                                </div>
                            </div>

                            <div class="mb-3 form-check d-flex">
                                {{ form.is_staff }}
                                <label class="form-check-label px-2" for="{{ form.is_staff.id_for_label }}">Staff Status</label>
                            </div>

                            <button type="submit" class="btn btn-success btn-block float-end">Update</button>
                        </form>
                </div>
                </div>
            </div>
        </div>
{% endblock content %}

Server/accounts/templates/users.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Users</title>
{% endblock title %}

{% block content %}
    {% block nav_links %}
        <span class="d-flex align-items-center mb-2">
            <a href="{% url 'orders:list_of_orders' %}" class="text-decoration-none text-secondary ">
                <i class='bx bx-home fs-5 text-secondary' ></i>
            </a>
            <i class='bx bx-chevron-right fs-5 text-secondary' ></i>
            <span class="text-secondary">All Users</span>
        </span>
    {% endblock nav_links %}

  {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning d-flex align-items-center" role="alert" id="alertMessage">
                <i class='bx bxs-check-circle text-success me-1'></i> {{ message|safe }}
            </div>
        {% endfor %}
        <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
        <script>
            $(document).ready(function () {
                setTimeout(function () {
                    $("#alertMessage").fadeOut("slow", function () {
                        $(this).remove();
                    });
                }, 4000);
            });
        </script>
  {% endif %}
<div class="col-12 shadow border p-4 mb-4 rounded h-100 overflow-auto">
    <a href="{% url 'accounts:access_user' %}" class="col-12 col-md-4 col-lg-2 btn nav-buttons d-flex align-items-center justify-content-center mb-3">
        <i class='bx bxs-circle me-2' ></i>
        Add New User
      </a>
    <table class="table align-middle mb-0 bg-white">
        <thead class="bg-light">
        <tr>
            <th>User</th>
            <th>Email</th>
            <th>User Status</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody class="shadow">
            {% for user in users %}
            <tr>
                <td>
                    <div class="d-flex align-items-center">
                        {% if user.is_staff %}
                            <img
                            src="{% static 'images/admin.png' %}"
                            class="rounded-circle"
                            alt=""
                            style="width: 45px; height: 45px"
                            />
                        {% else %}
                            <img
                                src="{% static 'images/manager.png' %}"
                                class="rounded-circle"
                                alt=""
                                style="width: 45px; height: 45px"
                                />
                        {% endif %}
                      <div class="ms-3">
                        <p class="fw-bold mb-1">{{ user.username  }}</p>
                        <p class="text-muted mb-0">{{ user.first_name }} {{ user.last_name }}</p>
                      </div>
                    </div>
                  </td>
                <td>{{ user.email }}</td>
                <td>
                    {% if user.is_staff %}
                        <div class="d-flex align-items-center">
                            <p class="m-0 pe-1">Admin</p>
                            <i class='bx bxs-badge-check fs-5' style='color:#17c70e'></i>
                        </div>
                    {% else %}
                        <div class="d-flex align-items-center">
                            <p class="m-0 pe-1">User</p>
                            <i class='bx bxs-badge-check fs-5' style='color:#3d73e7'></i>
                        </div>
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'accounts:update_user' user.pk %}" class="btn btn-link bg-light btn-sm btn-rounded text-decoration-none text-danger">
                        <i class='bx bx-edit-alt fs-4 text-secondary' ></i>
                    </a>
                    <a href="{% url 'accounts:delete_user' user.pk %}" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal{{ user.pk }}" class="btn btn-link bg-light btn-sm btn-rounded text-decoration-none text-danger">
                        <i class='bx bx-trash fs-4 text-danger' ></i>
                    </a>
                    {% include 'delete_user.html' %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <!-- Pagination -->
    {% if users.has_other_pages %}
        <div class="mt-3 d-flex justify-content-end">
            <ul class="pagination">
            {% if users.has_previous %}
                <li class="page-item">
                <a class="page-link" href="?page={{ users.previous_page_number }}">&laquo;</a>
                </li>
            {% endif %}
        
            {% for num in users.paginator.page_range %}
                <li class="page-item{% if num == users.number %} active{% endif %}">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
            {% endfor %}
        
            {% if users.has_next %}
                <li class="page-item">
                <a class="page-link" href="?page={{ users.next_page_number }}">&raquo;</a>
                </li>
            {% endif %}
            </ul>
        </div>
    {% endif %}
</div>
{% endblock content %}