Server/SEOBot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("orders.urls")),
]

Server/accounts/urls.py
from django.urls import path
from .views import CreateAccessUser, PasswordChangeView, password_success, UsersListView, UserDeleteView, UserUpdateView    

app_name = 'accounts'
urlpatterns = [
    path("access_user/", CreateAccessUser.as_view(), name="access_user"),
    path("password/", PasswordChangeView.as_view(), name="change_password"),
    path("users/", UsersListView.as_view(), name="users"),
    path("users/<int:pk>/delete/", UserDeleteView.as_view(), name="delete_user"),
    path("users/<int:pk>/update/", UserUpdateView.as_view(), name="update_user"),
]  

Server/orders/urls.py
from django.urls import path
from .views import *


app_name = 'orders'
urlpatterns = [
    # Order routes
    path("", ViewOrders.as_view(), name="list_of_orders"),
    path("result1", ViewKeyword.as_view(), name="ViewKeyword"),
    path('update-action/', update_order_action, name='update-action'),

    path("order/new/", CreateNewOrder.as_view(), name="create_order"),
    path("order/<int:pk>/delete/", DeleteOrder.as_view(), name="delete_order"),
    path("order/<int:pk>/update/", UpdateOrder.as_view(), name="update_order"),
    # Profile route
    path("profiles", ViewProfiles.as_view(), name="profile"),
    path("profile/new/", CreateNewProfile.as_view(), name="create_profile"),
    path("profile/<int:pk>/delete/", DeleteProfile.as_view(), name="delete_profile"),
    path("profile/<int:pk>/update/", UpdateProfile.as_view(), name="update_profile"),

    # API route
    path("api/get/orders/web", get_orders_web),
    path("api/get/random/user/web/<int:no>",get_random_proxy_details_web),
    path("api/get/random/user/mobile/<int:no>",get_random_proxy_details_mobile),
    path("api/get/orders/mobile", get_orders_mobile),
    path('update-reached-users/<int:pk>/', update_reached_users, name='update_reached_users'),
    path('update-reached-users-incomplete/<int:pk>/', update_reached_users_incomplete),
    path("api/set/profile/free/<int:pk>/",setProfileFree),
    path("api/get/number/of/profiles",get_number_of_profile_mobile),

    path('api/update-reached-numbers/<int:order_id>/', update_reached_users, name='update_reached_users'),
]

Server/orders/forms.py
from django import forms
from .models import Order,Profile
from datetime import datetime, timedelta


class CreateNewOrder(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreateNewOrder, self).__init__(*args, **kwargs)
        now = datetime.now()
        min_time = now.strftime('%Y-%m-%dT%H:%M')

        # Set minimum date and time
        self.fields['order_schedule'].widget.attrs['min'] = min_time

    class Meta:
        model = Order
        fields = ('domain_name', 'domain_type', 'click_domain_only', 'active', 'work_sec', 'avg_sec', 'num_users', 'order_schedule')
        widgets = {
            'domain_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Domain Name'}),
            'domain_type': forms.Select(attrs={'class': 'form-control'}),
            'click_domain_only': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'work_sec': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter Work Duration (seconds)', 'min': 30}),
            'avg_sec': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter Average Seconds per Page', 'min': 30}),
            'num_users': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Number of Users', 'min': 1}),
            'order_schedule': forms.DateTimeInput(attrs={'class': 'form-control', 'placeholder': 'Select Order Schedule', 'type': 'datetime-local'}),
        }

class UpdateOrder(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UpdateOrder, self).__init__(*args, **kwargs)
        now = datetime.now()
        min_time = now.strftime('%Y-%m-%dT%H:%M')

        # Set minimum date and time
        self.fields['order_schedule'].widget.attrs['min'] = min_time


    class Meta:
        model = Order
        fields = ('domain_name',  'domain_type', 'active', 'click_domain_only', 'work_sec', 'avg_sec', 'num_users', 'order_schedule')
        widgets = {
            'domain_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Domain Name'}),
            'domain_type': forms.Select(attrs={'class': 'form-control'}),
            'click_domain_only': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'work_sec': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter Work Duration (seconds)', 'min': 30}),
            'avg_sec': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter Average Seconds per Page', 'min': 30}),
            'num_users': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter Number of Users', 'min': 1}),
            'order_schedule': forms.DateTimeInput(attrs={'class': 'form-control', 'placeholder': 'Select Order Schedule', 'type': 'datetime-local'}),
        }

class CreateNewProfile(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("proxy","UserAgent","domain_type","serverID")
        widgets = {
            "proxy": forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Proxy:user:password',"autocomplete":"off"}),
            "UserAgent": forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter User Agent',"autocomplete":"off"}),
            'domain_type': forms.Select(attrs={'class': 'form-control'}),
        }
class UpdateProfiles(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("proxy","UserAgent","domain_type","serverID")
        widgets = {
            "proxy": forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Proxy:user:password',"autocomplete":"off"}),
            "UserAgent": forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter User Agent',"autocomplete":"off"}),
            'domain_type': forms.Select(attrs={'class': 'form-control'}),
        }


class OrderActionForm(forms.Form):
    keyword_id = forms.IntegerField(widget=forms.HiddenInput())
    order_id = forms.IntegerField(widget=forms.HiddenInput())
    action = forms.CharField()
    second_action = forms.CharField(required=False)

Server/orders/views.py
from django.forms import BaseModelForm
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, DeleteView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from .models import *
from django.urls import reverse_lazy
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.core.serializers import serialize
import requests
import random
from django.http import HttpResponseRedirect

from django.db.models import Value
from django.db.models.functions import Coalesce


from django.views.decorators.csrf import csrf_exempt
from datetime import timedelta

def get_location_and_timezone(ip_address):
    # Using a geolocation service API (like ipgeolocation, ipinfo, etc.)
    # Here I use 'ip-api.com' for demonstration; you should use your preferred geolocation service
    # Make sure to handle the API key and rate limiting as per your service's requirements
    response = requests.get(f'http://ip-api.com/json/{ip_address}?fields=status,message,country,countryCode,region,regionName,city,zip,lat,lon,timezone,query')
    
    if response.status_code == 200:
        data = response.json()
        if data['status'] == 'success':
            # Return the necessary fields
            return {
                'country': data.get('country', ''),
                'countryCode': data.get('countryCode', ''),
                'region': data.get('region', ''),
                'regionName': data.get('regionName', ''),
                'city': data.get('city', ''),
                'zip': data.get('zip', ''),
                'lat': data.get('lat', 0),
                'lon': data.get('lon', 0),
                'timezone': data.get('timezone', ''),
                'query': data.get('query', '')
            }
        else:
            raise Exception("API returned an error: " + data.get('message', 'No message'))
    else:
        response.raise_for_status()

    return None

def get_orders(request, domain_type):
    keywords = Keyword.objects.filter(keyword__active=True, keyword__domain_type=domain_type, status__in=["Waiting", "In Progress"]) 
    keywords = keywords.annotate(
    nearest_date=Coalesce('keyword__order_schedule', Value(datetime.min))
    ).order_by('nearest_date')
    clean_data = []
    for i, keyword in enumerate(keywords):
        clean_data.append({
            "id": keyword.keyword.id,
            'domain_name': f"https://{keyword.keyword.domain_name}" if not keyword.keyword.domain_name.startswith("https://") else keyword.keyword.domain_name,
            'domain_type': keyword.keyword.domain_type,
            'work_sec': keyword.keyword.work_sec,
            'max_workers': keyword.keyword.WorkerRequired(),
            'reached_users': keyword.keyword.reached_users,
            'total_users': keyword.keyword.num_users,
            "order_schedule": keyword.keyword.order_schedule,
            'action': keyword.keyword.action,
            'click_domain_only': keyword.keyword.click_domain_only,
            'second_action': keyword.keyword.second_action,
            'has_sponsored': keyword.has_sponsored,
            'has_business':keyword.has_business,
            'has_sponsored_business': keyword.has_sponsored_business,
            'status': keyword.status
        })
        break
    # Return the clean data as a JsonResponse
    return clean_data

def get_orders_web(request):
    data = get_orders(request, "web")
    return JsonResponse(data, safe=False)

def get_orders_mobile(request):
    data = get_orders(request, "mobile")
    return JsonResponse(data, safe=False)


def update_reached_users(request, pk):
    """ Function to increase the reached_user number in models.py """
    order = Order.objects.get(pk=pk)
    order.increment_reached_users() 
    return JsonResponse({'success': True})

def update_reached_users_incomplete(request, pk):
    """ Function to increase the reached_user number in models.py """
    order = Order.objects.get(pk=pk)
    order.decrement_reached_users() 
    return JsonResponse({'success': True})


# Orders View
class ViewOrders(LoginRequiredMixin, TemplateView):
    template_name = "orders.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order_list = Order.objects.all().filter(no_business_or_sponsor=False).order_by('-id')

        column = self.request.GET.get('column')
        query = self.request.GET.get('query')

        if column and query:
            if column == 'domain_name':
                order_list = order_list.filter(domain_name__icontains=query)
            elif column == 'proxy':
                order_list = order_list.filter(proxy__icontains=query)
            elif column == 'active':
                query_bool = query.lower() == 'true'
                order_list = order_list.filter(active=query_bool)
            elif column == 'work_sec':
                order_list = order_list.filter(work_sec__icontains=query)
            elif column == 'avg_sec':
                order_list = order_list.filter(avg_sec__icontains=query)
            elif column == 'num_users':
                order_list = order_list.filter(num_users__icontains=query)
        
        # Pagination
        page = self.request.GET.get('page', 1)
        paginator = Paginator(order_list, 5) 

        try:
            order_list = paginator.page(page)
        except PageNotAnInteger:
            order_list = paginator.page(1)
        except EmptyPage:
            order_list = paginator.page(paginator.num_pages)

        context['order_list'] = order_list
        return context
    




class ViewKeyword(LoginRequiredMixin, TemplateView):
    template_name = "result1.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        keyword_list = Keyword.objects.filter(status="Waiting")
        
        # Pagination
        page = self.request.GET.get('page', 1)
        paginator = Paginator(keyword_list, 10) 

        try:
            keyword_list = paginator.page(page)
        except PageNotAnInteger:
            keyword_list = paginator.page(1)
        except EmptyPage:
            keyword_list = paginator.page(paginator.num_pages)

        context['keyword_list'] = keyword_list
        return context


class CreateNewOrder(CreateView):
    model = Order
    template_name = "create_new_order.html"
    form_class = CreateNewOrder

    def form_valid(self, form):
        if form.cleaned_data.get('click_domain_only'):
            form.instance.active = True
        domain_name = form.cleaned_data['domain_name']
        messages.success(self.request, f"Domain for&nbsp;<strong>{domain_name}</strong>&nbsp;added! Proceed to <strong> Orders in progress </strong> to decide the next steps.")

        response = super().form_valid(form)
        order = Order.objects.get(id=form.instance.id)
        if order.no_business_or_sponsor:
            messages.error(self.request, f"Domain &nbsp;<strong>{domain_name}</strong>&nbsp;will be ignored! No business or sponsor found.")
        # Add an error message based on a condition
        # if ():  # Replace this with your actual condition
        #     messages.error(self.request, "An error occurred after creating the order.")

        return response
    
class CreateNewProfile(CreateView):
    model = Profile
    template_name = "create_new_profile.html"
    form_class = CreateNewProfile
    success_url =  reverse_lazy("orders:profile")


    def form_valid(self, form):
        profile = form.save(commit=False)

        proxy_string = form.cleaned_data['proxy']
        proxy_parts = proxy_string.split(':')
        if len(proxy_parts) >= 4:
            proxy_ip, proxy_port, proxy_username, proxy_password = proxy_parts[:4]

            geo_data = get_location_and_timezone(proxy_ip)
            if geo_data:
                profile.save()  # Commit the profile to the database

                ProxyDetail.objects.update_or_create(
                    profile=profile,
                    defaults={
                        'status': 'valid',
                        'country': geo_data['country'],
                        'countryCode': geo_data['countryCode'],
                        'region': geo_data['region'],
                        'regionName': geo_data['regionName'],
                        'city': geo_data['city'],
                        'zip': geo_data['zip'],
                        'lat': geo_data['lat'],
                        'lon': geo_data['lon'],
                        'timezone': geo_data['timezone'],
                        'query': proxy_ip,
                        'proxyusername': proxy_username,
                        'proxy_password': proxy_password
                    }
                )

                messages.success(self.request, f"Profile for <strong>{proxy_ip}</strong> added successfully!")
            else:
                messages.error(self.request, "Failed to fetch geo data for the provided proxy.")

        else:
            messages.error(self.request, "Invalid proxy format.")

        return super().form_valid(form)
        

class DeleteOrder(LoginRequiredMixin, DeleteView):
    model = Order
    template_name = "delete_order.html"
    success_url = reverse_lazy("orders:list_of_orders")

    def form_valid(self, form):
        order = self.get_object()
        domain_name = order.domain_name

        response = super().form_valid(form)
        messages.success(self.request, f"Domain for&nbsp;<strong>{domain_name}</strong>&nbsp;has been deleted succesfully!")
        return response

class DeleteProfile(LoginRequiredMixin,DeleteView):
    model = Profile
    template_name = "delete_profile.html"

Server/orders/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Box Icons -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anta&display=swap" rel="stylesheet">

    
    <!-- Navbar CSS  -->
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/buttons.css' %}">

    {% block login_link %}
    {% endblock login_link %}

    {% block title %}
        <title>SEO BOT</title>
    {% endblock title %}
    
  </head>
  <body class="bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% if user.is_authenticated %}
                <!-- Navbar -->
                <nav class="navbar navbar-expand-lg navbar-scroll fixed-top shadow-sm border-bottom border-secondary mb-5">
                    <div class="col-md-3 ms-3 d-flex align-items-center">
                        <a class="navbar-brand text-dark d-flex align-items-center" href="{% url 'orders:list_of_orders' %}">
                            <i class='bx bxs-bot me-1 fs-3 mb-1 text-light'></i>
                            <span class="h5 m-0 text-light">SEO-BOT</span>
                        </a>                        
                    </div>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto">
                            <div class="col-md-9 mx-4 d-flex justify-content-end align-items-center">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-dark bg-white text-dark dropdown-toggle d-flex align-items-center" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class='bx bxs-hand fs-4 px-1 text-dark'></i>
                                        <span class="text-dark">Hi, {{ user.username }}</span>
                                    </button>
                                    <ul class="dropdown-menu dropdown-menu-end">
                                        {% if user.is_staff %} 
                                            <li><a class="dropdown-item" href="{% url 'accounts:users' %}">All Users</a></li>
                                        {% endif %}
                                        <li><a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change Password</a></li>
                
                                        <form action="{% url 'logout' %}" method="post">
                                            {% csrf_token %}
                                            <div class="dropdown-divider"></div>
                                            <button type="submit" class="dropdown-item">Log out</button>
                                        </form>
                                    </ul>
                                </div>
                            </div>
                        </ul>
                    </div>
                </nav>
                <!-- Navbar -->
                {% endif %}
            </div>
        </div>

        <div class="row mt-3">
            {% block content %}
                {% block nav_links %}
                {% endblock nav_links %}
            {% endblock content %}
        </div>
        
        
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

Server/orders/templates/orders.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>SEO BOT - Orders</title>
{% endblock title %}

{% block content %}
  {% if messages %}
      {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger d-flex align-items-center" role="alert" id="alertMessage">
                <i class='bx bxs-bell-ring text-danger me-1'></i> {{ message|safe }}
            </div>
        {% elif message.tags == 'success' %}
            <div class="alert alert-success d-flex align-items-center" role="alert" id="alertMessage">
                <i class='bx bxs-check-circle text-success me-1'></i> {{ message|safe }}
            </div>
        {% endif %}
      {% endfor %}
          <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
          <script>
              $(document).ready(function () {
                  setTimeout(function () {
                      $("#alertMessage").fadeOut("slow", function () {
                          $(this).remove();
                      });
                  }, 4000);
              });
          </script>
    {% endif %}

<div class="col-12 border shadow-sm p-4 mb-4 rounded h-100 overflow-auto">
  <div class="row mb-3">
    <div class="col-12 col-md-6 col-lg-3">
      <a href="{% url 'orders:profile' %}" class="btn nav-buttons w-75 d-flex align-items-center justify-content-center">
        <i class='bx bxs-circle me-2' ></i>
        Profiles
      </a>
    </div> 
    <div class="col-12 col-md-6 col-lg-3">
      <a href="{% url 'orders:create_order' %}" class="btn nav-buttons w-75 d-flex align-items-center justify-content-center">
        <i class='bx bxs-circle me-2' ></i>
        Add New Order
      </a>
  </div>
  <div class="col-12 col-md-6 col-lg-3">
      <a href="{% url 'orders:ViewKeyword' %}" class="btn nav-buttons w-75 d-flex align-items-center justify-content-center">
        <i class='bx bxs-circle me-2' ></i>
        Orders in Progress
      </a>
  </div>
  </div>

  <div class="input-group mt-2 mb-2">
      {% include 'search_orders.html' %}
  </div>

  <table class="table align-middle mb-0 bg-white">
      <thead class="bg-light">
        <tr>
          <th>ID</th>
          <th>Domain Name</th>
          <th>Proxy Name</th>
          <th>Device Type</th>
          <th>Sec(Work)</th>
          <th>Sec(Avg)</th>
          <th>Number of Users</th>
          <th>Reached User</th>
          <th>Schedule</th>
          <th>Active</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody class="shadow">
        {% for order in order_list %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ order.domain_name }}</td>
              <td>{{ order.proxy }}</td>
              <td>{{ order.domain_type }}</td>
              <td>{{ order.work_sec }}</td>
              <td>{{ order.avg_sec }}</td>
              <td>{{ order.num_users }}</td>
              <td>{{ order.reached_users }}</td>
              <td>{{ order.order_schedule }}</td>
              <td>{{ order.active}}</td>
              <td class="d-flex">
                <a href="#" class="btn btn-link bg-light btn-sm btn-rounded text-decoration-none text-danger" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal{{ order.pk }}">
                    <i class='bx bx-trash fs-4 text-danger' ></i>
                </a>
                {% include 'delete_order.html' %}

                <a href="{% url 'orders:update_order' order.pk %}" class="btn btn-link bg-light btn-sm btn-rounded text-decoration-none">
                    <i class='bx bx-edit-alt fs-4 text-success' ></i>
                </a>
              </td>
            </tr>
        {% endfor %}
      </tbody>
  </table>

    <!-- Pagination -->
    {% if order_list.has_other_pages %}
      <div class="mt-3 d-flex justify-content-end">
        <ul class="pagination">
          {% if order_list.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ order_list.previous_page_number }}">&laquo;</a>
            </li>
          {% endif %}
      
          {% for num in order_list.paginator.page_range %}
            <li class="page-item{% if num == order_list.number %} active{% endif %}">
              <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
          {% endfor %}
      
          {% if order_list.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ order_list.next_page_number }}">&raquo;</a>
            </li>
          {% endif %}
        </ul>
      </div>
    {% endif %}
</div>
{% endblock content %}

Server/orders/templates/profile.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>SEO BOT - Orders</title>
{% endblock title %}

{% block content %}
  {% if messages %}
      {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger d-flex align-items-center" role="alert" id="alertMessage">
                <i class='bx bxs-bell-ring text-danger me-1'></i> {{ message|safe }}
            </div>
        {% elif message.tags == 'success' %}
            <div class="alert alert-success d-flex align-items-center" role="alert" id="alertMessage">
                <i class='bx bxs-check-circle text-success me-1'></i> {{ message|safe }}
            </div>
        {% endif %}
      {% endfor %}
          <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
          <script>
              $(document).ready(function () {
                  setTimeout(function () {
                      $("#alertMessage").fadeOut("slow", function () {
                          $(this).remove();
                      });
                  }, 4000);
              });
          </script>
    {% endif %}

<div class="col-12 border shadow-sm p-4 mb-4 rounded h-100 overflow-auto">
  <div class="row mb-3">
    <div class="col-12 col-md-6 col-lg-3">
      <a href="{% url 'orders:list_of_orders' %}" class="btn nav-buttons w-75 d-flex align-items-center justify-content-center">
        <i class='bx bxs-circle me-2' ></i>
          Orders
    </a>
    </div> 
    <div class="col-12 col-md-6 col-lg-3">
      <a href="{% url 'orders:create_profile' %}" class="btn nav-buttons w-75 d-flex align-items-center justify-content-center">
        <i class='bx bxs-circle me-2' ></i>
        Add New Profile
    </a>
    </div> 
  </div>

  <div class="input-group mt-2 mb-2">
      {% include 'search_orders.html' %}
  </div>

  <table class="table align-middle mb-0 bg-white">
      <thead class="bg-light">
        <tr>
          <th>ID</th>
          
          <th>Proxy Name</th>
          <th>User Agent</th>
          <th>Domain Type</th>
          <th>Server</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody class="shadow">
        {% for order in order_list %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ order.proxy }}</td>
              <td>{{ order.UserAgent }}</td>
              <td>{{ order.domain_type }}</td>
              <td>{{ order.serverID }}</td>
              <td class="d-flex">
                <a href="#" class="btn btn-link bg-light btn-sm btn-rounded text-decoration-none text-danger" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal{{ order.pk }}">
                    <i class='bx bx-trash fs-4 text-danger' ></i>
                </a>
                {% include 'delete_profile.html' %}

                <a href="{% url 'orders:update_profile' order.pk %}" class="btn btn-link bg-light btn-sm btn-rounded text-decoration-none">
                    <i class='bx bx-edit-alt fs-4 text-success' ></i>
                </a>
              </td>
            </tr>
        {% endfor %}
      </tbody>
  </table>

    <!-- Pagination -->
    {% if order_list.has_other_pages %}
      <div class="mt-3 d-flex justify-content-end">
        <ul class="pagination">
          {% if order_list.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ order_list.previous_page_number }}">&laquo;</a>
            </li>
          {% endif %}
      
          {% for num in order_list.paginator.page_range %}
            <li class="page-item{% if num == order_list.number %} active{% endif %}">
              <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
          {% endfor %}
      
          {% if order_list.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ order_list.next_page_number }}">&raquo;</a>
            </li>
          {% endif %}
        </ul>
      </div>
    {% endif %}
</div>
{% endblock content %}